### ISSUE TITLE
Roadmap to version 1.0

### ISSUE THREAD

**Issue by luxigo** [FoxelSA/freepano#6]
- [ ] Documentation
- [x] Navigation arrows in-scene
- [x] Navigation arrows on overlay
- [x] Load visible tiles first
- [x] Load tiles progressively
- [x] ~~Switch pyramid levels progressively~~

**Comment by prston** [comment]
Commit 6794f3b

* Load visible tiles first
* Load tiles progressively

**Comment by prston** [comment]
Not yet in the pipeline...

* Switch pyramid levels progressively
